// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnwekpnwbtfkfowbzcoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ud2VrcG53YnRma2Zvd2J6Y29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjczMDUsImV4cCI6MjA3Mjc0MzMwNX0.-EMsy3Mzx3A5JwVm1kk13X4XFrr2n4lSG9TDwE-uGlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});